### PR TITLE
[B] Fix footer category label position

### LINKED ISSUE #478: Footer subject bar in reader isn't positioned correctly
image

Compare to comps.

### PR DESCRIPTION
**Pull request by naomiyaki**
[Fixes #478]

### CODE REVIEW

File: client/src/components/reader/Section/Label.js [hunk 1]
```diff
@@ -1,11 +1,39 @@
...
+  }
+
+  toggleFixed() {
+    // Show or hide label depending on footer visibility
+    const staticRect = this.staticLabel.getBoundingClientRect();
+    this.setState({
+      fixed: staticRect.bottom > window.innerHeight
+    });
+  }
+
```
Comment (zdavis) [inline client/src/components/reader/Section/Label.js]: I think that what you're doing with `toggleFixed` could be simplified:

```
  componentDidMount() {
    window.addEventListener("scroll", this.throttledFixed);
  }

  toggleFixed = throttle(() => {
    // Show or hide label depending on footer visibility
    const staticRect = this.staticLabel.getBoundingClientRect();
    this.setState({
      fixed: staticRect.bottom > window.innerHeight
    });
  }, 200);
```

File: client/src/components/reader/Section/Label.js [hunk 2]
```diff
@@ -18,11 +46,31 @@ export default class Label extends PureComponent {
     if (this.isPublished()) return null;
     if (!this.category()) return null;
 
+    const fixedLabelClass = classNames({
+      "section-category-label": true,
+      fixed: true,
+      hidden: !this.state.fixed
+    });
+
```
Comment (zdavis) [inline client/src/components/reader/Section/Label.js]: This could be condensed and simplified by taking advantage of className's ability to mix arg types and some destructuring:

```
const hidden = this.state.fixed;
const fixedLabelClass = classNames("section-category-label", "fixed", { hidden })
```

**Comment by zdavis** [comment]
@naomiyaki please rebase into a single commit, and I will accept.
